---
- name: Terraform plan
  delegate_to: localhost
  connection: local
  terraform:
    project_path: ~/proxmox_tf/
    plan_file:
    force_init: true
    state: "planned"
    backend_config_files: "{{ ocp_proxmox_infra_tfstate_path }}" 
  environment:
    PM_USER: "{{ vault_tf_proxmox_user }}@pve"
    PM_PASS: "{{ vault_tf_proxmox_pass }}"
