---

- name: Check role exists
  shell: pveum role list | grep {{ tf_role_name }}
  register: pverole
  failed_when: false
  changed_when: false

- name: Ensure user roles
  when: "pverole.stdout == ''"
  block:
    - name: Create role
      ansible.builtin.shell: pveum role add {{ tf_role_name }} -privs "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit"
    - name: Create user
      ansible.builtin.shell: pveum user add {{ vault_tf_proxmox_user }}@pve --password {{ vault_tf_proxmox_pass }}
      no_log: true
    - name: User role map
      ansible.builtin.shell: pveum aclmod / -user {{ vault_tf_proxmox_user }}@pve -role {{ tf_role_name }}

